### ISSUE TITLE
Tokenizer 관련 문의

### ISSUE THREAD

**Issue by limhasic** [Marker-Inc-Korea/K-G-OAT#1]
KoAlpaca 5.8b가 베이스 모델이며, Tokenizer는 Polyglot5.8b의 Tokenizer를 사용하셨는데, 다른 데이터셋을 사용한다면, 토크나이저도 바뀌어야할까요?

**Comment by DopeorNope-Lee** [comment]
답변이 늦었네요 문의 감사합니다.

다른 데이터셋이 아니라, 다른 베이스 모델을 활용하신다면, 토크나이저를 그 모델에 맞게 토크나이저를 변경하시면 됩니다.

데이터셋이 다르더라도 베이스 모델이 같으면, 토크나이저는 그대로 활용하시면 좋습니다.

토크나이저의 기능은 보통 문자열로 구성된 데이터셋을 숫자형으로 바꾸기 위해서 vocab이라는 단어장을 가지고 그 단어에 해당하는 숫자로 문장을 바꾸어 줍니다 (반대의 상황에서도 이용가능하겠지요).

그렇기 때문에, 보통 한 베이스 모델이 이러한 토크나이저를 썼다면, 제가 단어장을 더 키우지 않는한, 같은 토크나이저를 저는 씁니다.

하지만 사람마다 접근 방식이 다 달라서, 혹시 원하는 방향성이 있다면 Implement 하시면 좋은 결과가 있을것으로 생각됩니다!

답변이 늦어 죄송합니다~!

**Comment by limhasic** [comment]
> 답변이 늦었네요 문의 감사합니다.
> 
> 다른 데이터셋이 아니라, 다른 베이스 모델을 활용하신다면, 토크나이저를 그 모델에 맞게 토크나이저를 변경하시면 됩니다.
> 
> 데이터셋이 다르더라도 베이스 모델이 같으면, 토크나이저는 그대로 활용하시면 좋습니다.
> 
> 토크나이저의 기능은 보통 문자열로 구성된 데이터셋을 숫자형으로 바꾸기 위해서 vocab이라는 단어장을 가지고 그 단어에 해당하는 숫자로 문장을 바꾸어 줍니다 (반대의 상황에서도 이용가능하겠지요).
> 
> 그렇기 때문에, 보통 한 베이스 모델이 이러한 토크나이저를 썼다면, 제가 단어장을 더 키우지 않는한, 같은 토크나이저를 저는 씁니다.
> 
> 하지만 사람마다 접근 방식이 다 달라서, 혹시 원하는 방향성이 있다면 Implement 하시면 좋은 결과가 있을것으로 생각됩니다!
> 
> 답변이 늦어 죄송합니다~!
