### ISSUE TITLE
torch 버전 문의

### ISSUE THREAD

**Issue by LAB-703** [Marker-Inc-Korea/K-G-OAT#2]
안녕하세요, @dopeornope-Lee 

Training_IA3.ipynb 코드를 돌려보던 도중에 아래와 같은 오류가 발생하였습니다.
torch 버전의 문제인 듯한데 2.0.0에서는 오류가 났고, 1.13.0에서는 문제 없이 돌아갑니다.
1. 라이브러리 다운로드 부분에 torch(구동 가능한 최신 버전)와 scipy이 추가되면 좋을 듯합니다.
코드 공유 감사합니다.

`import transformers

tokenizer.pad_token = tokenizer.eos_token

trainer = transformers.Trainer(
    model=model,
    train_dataset=data["train"],
    args=transformers.TrainingArguments(
        per_device_train_batch_size=2,
        gradient_accumulation_steps=1,
        num_train_epochs=4,
        max_steps=15930, # 가장 최적화된 15930 step까지 훈련되었습니다.
        learning_rate=5e-5,
        fp16=True,
        logging_steps=10,
        output_dir="outputs",
        optim='adamw_torch'),
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False),
)
model.config.use_cache = False  # silence the warnings. Please re-enable for inference!
trainer.train()`

RuntimeError: "_amp_foreach_non_finite_check_and_unscale_cuda" not implemented for 'BFloat16'

**Comment by DopeorNope-Lee** [comment]
감사합니다. 우선 기본적인 제 환경에서 세팅하다보니, 라이브러리 버전을 신경쓰지 못했네요. 참고하여 향후 다른 업데이트들에 대해서 언급하도록 하겠습니다!
